### ISSUE TITLE
Create LICENSE.txt

### ISSUE THREAD

**Issue by heezyxiv** [KingSora/KingSora.github.io#7]
The OverlayScrollbars website links to the MIT wikipedia page but I don't see a license file anywhere in the repo or on the website. Can you add a LICENSE.txt for MIT? (or whichever license you prefer)
This might help: https://help.github.com/en/articles/licensing-a-repository

**Comment by KingSora** [comment]
Hi!

You might thought that this repo is the plugins repo, but its just the repo for the Github-page. The [OverlayScrollbars Github repo](https://github.com/KingSora/OverlayScrollbars) has a LICENSE file for each provided package.

**Comment by heezyxiv** [comment]
Thanks! Apologies for that.
